<script>
    const cacheAsync = (promiseGenerator, symbol) => {
    const cache = new Map();
    return async (params) => {
      return new Promise((resolve, reject) => {
        symbol = symbol || params;
        let cacheCfg = cache.get(symbol);
        if (!cacheCfg) {
          cacheCfg = {
            res: null,
            exector: [{ resolve, reject }],
          };
          cache.set(symbol, cacheCfg);
        } else {
          // 命中缓存
          if (cacheCfg.res) {
            return resolve(cacheCfg.res)
          }
          cacheCfg.exector.push({ resolve, reject });
        }

        const { exector } = cacheCfg;
        
        // 处理并发
        // 拿第一个请求
        if (exector.length === 1) {
          const next = async () => {
            try {
              if (!exector.length) return;
              const reqData = await promiseGenerator(params);
              // 如果成功了，那么直接resolve掉剩余同样的请求
              while (exector.length) {
                exector.shift().resolve(reqData);
              }
              cacheCfg.res = reqData;
            } catch (error) {
              // 如果失败了 那么这个promise的则为reject
              const { reject } = exector.shift();
              reject(error);
              next();
            }
          };
          next();
        }
      });
    };
  };

  var fetch2 = cacheAsync(fetchData, "test2");

  async function fetchData(a) {
    const data = await fetch("//127.0.0.1:3000/test");
    const d = await data.json();
    console.log(d);
    return d;
  }

  console.log(fetch2(2));
  console.log(fetch2(2));
  console.log(fetch2(2));
  console.log(fetch2(2));
  console.log(fetch2(2));
  console.log(fetch2(2));

</script>
